---
Name: ecommerce
Before: 'mysite/*'
After: 'framework/*','cms/*'
---

DevelopmentAdmin:
  extensions:
    - EcommerceDevelopmentAdminDecorator

Member:
  extensions:
    - EcommerceRole

SiteTree:
  extensions:
    - EcommerceSiteTreeExtension

Payment:
  extensions:
    - EcommercePayment


Page_Controller:
  extensions:
    - EcommerceSiteTreeExtension_Controller

Money:
  extensions:
    - EcommerceMoney

OrderEmailRecord_Review:
  url_segment: "ecommerce-email-preview"

EcommerceDatabaseAdmin:
  allowed_actions:
    - runTask

LeftAndMain:
  extra_requirements_css:
    - ecommerce/css/ecommercecmsfixes.css

---
Only:
  environment: 'dev'
---
EcommercePayment:
  supported_methods:
    EcommercePayment_TestSuccess : Success
    EcommercePayment_TestPending : Pending
    EcommercePayment_TestFailure : Failure
